### ISSUE TITLE
UI Elements期

### ISSUE THREAD

**Issue by ghost** [neon-izm/before_join_socialgame#10]
このリポジトリでやられようとしていることは、とても興味深いです
私もコミットできたらなと考えております

気づいたことがあります
本来はPRであったかもしれませんが、ISSUEでお伝えいたします

こちらですが
https://github.com/neon-izm/before_join_socialgame/blob/master/website/docs/doc3.md
＞UI Elements期

名前がUI Toolkitとなりました
https://forum.unity.com/threads/renaming-uielements-to-ui-toolkit.854245/

こちらの名称にするのが適切かと思いました
いかがでしょうか

**Comment by neon-izm** [comment]
@itouh2-i0plus さん、 対応しました。旧名称も併記しておくことで、ググりやすさを担保しておこうと思います。

https://github.com/neon-izm/before_join_socialgame/commit/34d4aaf402e49d7a8f90abd24a8b6cacf8e59763


pull reqでも大丈夫ですし、こういう事であればissueでも大丈夫です。
