### ISSUE TITLE
[question] APIのレスポンスのステータスコードの取り扱いについて

### ISSUE THREAD

**Issue by EndoIsamu** [neon-izm/before_join_socialgame#15]
こんにちは
1章の**HTTPのヘッダ、ボディ、request、response**の項を読んでちょっとした疑問が生まれたので質問させてください．

外部のWeb APIを使っていると，ステータスコードをレスポンスボディに含む仕様のAPIが結構あったりします（正直この仕様の意義もよく分からないのですが...）
ここで，サンプルコードに`var responseCode = (int)request.responseCode;`と載っているのを見ると，ソシャゲで用意するAPIは普通にレスポンスヘッダのステータスコードを活用している（それで全く問題ない），という認識で良いでしょうか？

**Comment by neon-izm** [comment]
サーバサイドの実装による部分が多いかもしれません。
あるいは、httpステータスコードではなく、APIサーバ側で独自定義したステータスコードがある、という可能性もあります。

Http1.0規格に沿った実装のAPIサーバと通信する際は上記のコードで問題ないと思います。

例えばどんな例がありますか？可能なら見てみたいです。

**Comment by EndoIsamu** [comment]
なるほど，ここらへんは必要に応じて使い分ければいい，みたいな感じなのですね．

> 例えばどんな例がありますか？可能なら見てみたいです。

最近使ったものだと，[COTOHA 文タイプ判定API](https://api.ce-cotoha.com/contents/reference/apireference.html#sentence)のレスポンスに`status`の項目がありました．
また，[Google Geocoding API](https://developers.google.com/maps/documentation/geocoding/start)のレスポンスにも`status`というキーがありますね．

ただ，いま詳しく見てみると，確かにHTTPのステータスコードをそのまま返しているのではなく，API側で独自定義したステータス（コード）を返しているようでした．
なので，これらのステータスコードはアプリ固有の条件分岐を想定したものであり，HTTPのステータスコードとは完全に別のものとして考えるべきだったようです．すみません，勉強不足でした．

**Comment by neon-izm** [comment]
はい、HTTPステータスコードだけでなく、jsonレスポンス内に追加でSDKやサービス独自のステータスコードを定義しておく、というのはよくあるパターンですね。

良い質問ありがとうございます！
