### ISSUE TITLE
クライアント側のデータは改ざんされる可能性がある

### ISSUE THREAD

**Issue by osakanataro** [neon-izm/before_join_socialgame#23]
「この文書の全体の流れ」に「ソーシャルゲームでは基本的に主なデータをサーバ側で持っていて」と書いてあるが、なんでそういう作りになっているのかが述べられていない。
「入門以前」なので、どこかに明記した方が良いのでは、と思う
プルリクにするかどうか迷ったけど、Issueで上げてみる

入れるのであれば１章の「認証って何」の前あたり？

### クライアント上のデータは信頼してはいけない
これまでのゲーム運営の歴史上、クライアント側にセーブデータを置くと改ざんされてしまい運営が成り立たないことが分かっています。
このため、基本的にサーバ側がデータを持っていて、クライアント側におくものは書き換えられてもそれほど問題ないものと、各ユーザの認証に関わるデータとなります。

例えば、魔法石の所持数データを表示の為にクライアント上に保存(キャッシュ)してもよいが、実際に使う場合は必ずサーバ側に問い合わせるようにします。
ここでそのリクエストが不正なものでないことを確認するための手法として次の「認証」があります。

**Comment by osakanataro** [comment]
メッセージの未読管理はクライアント側で管理しても良い（サーバ側で全部を管理するとサーバ側データ量が増えるので）
ただし、メッセージ内にアイテム付与があった場合、未読管理とは別にアイテム付与が複数回実行されないようにサーバ側処理も考える。
これを間違えると未読管理を初期化することで、再度アイテムをもらえてしまいます。

**Comment by neon-izm** [comment]
@osakanataro さんありがとうございます！！
確かに認証が必要、の前あたりにこの記載があると良いですね。文章そのままで乗せても問題ないクオリティだと思うので、載せちゃって良いですか！

**Comment by osakanataro** [comment]
OKです

**Comment by neon-izm** [comment]
close https://github.com/neon-izm/before_join_socialgame/commit/84a0dcb1991ad2b4ad99ec58ff8ea18434649abc
